package pl.praktykiatrem.game.tictactoe.graphic.panels;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JPanel;

import pl.praktykiatrem.game.battleship.files.TTIcons;
import pl.praktykiatrem.game.tictactoe.rules.Sign;

public class ButtonPanel extends JPanel {
	private GamePanel controller;

	/**
	 * Creates new form TTButtonPanel
	 */
	public ButtonPanel(GamePanel superVisor) {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		goToMenuButton = new javax.swing.JButton();
		signLabel = new javax.swing.JLabel();
		signLabel.setAlignmentX(CENTER_ALIGNMENT);
		signLabel.setAlignmentY(CENTER_ALIGNMENT);

		setLayout(null);

		goToMenuButton.setText("Przejdz do menu");
		goToMenuButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent evt) {
				controller.abortGame();
			}
		});
		add(goToMenuButton);
		goToMenuButton.setBounds(0, 0, 200, 100);

		add(signLabel);
		signLabel.setBounds(200, 0, 100, 100);
	}// </editor-fold>

	public void setSignIcon(Sign sign) {
		signLabel.setIcon(TTIcons.getBigIcon(sign));
	}

	@Override
	public Dimension getPreferredSize() {
		return new Dimension(300, 100);
	}

	@Override
	public Dimension getMinimumSize() {
		return new Dimension(300, 100);
	}

	@Override
	public Dimension getMaximumSize() {
		return new Dimension(300, 100);
	}

	// Variables declaration - do not modify
	private javax.swing.JButton goToMenuButton;
	private javax.swing.JLabel signLabel;
	// End of variables declaration
}
