package pl.praktykiatrem.game.tictactoe.graphic;

import java.awt.Dimension;

import javax.swing.JPanel;

import pl.praktykiatrem.game.battleship.files.TTIcons;

public class ButtonPanel extends JPanel {
	/**
	 * Creates new form TTButtonPanel
	 */
	public ButtonPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		goToMenuButton = new javax.swing.JButton();
		signLabel = new javax.swing.JLabel();

		setLayout(null);

		goToMenuButton.setText("Przejdz do menu");
		add(goToMenuButton);
		goToMenuButton.setBounds(0, 0, 200, 100);

		add(signLabel);
		signLabel.setBounds(200, 0, 100, 100);
	}// </editor-fold>

	public void setSignIcon(int type) {
		signLabel.setIcon(TTIcons.getIcon(type));
	}

	@Override
	public Dimension getPreferredSize() {
		return new Dimension(300, 100);
	}

	@Override
	public Dimension getMinimumSize() {
		return new Dimension(300, 100);
	}

	// Variables declaration - do not modify
	private javax.swing.JButton goToMenuButton;
	private javax.swing.JLabel signLabel;
	// End of variables declaration
}
