package pl.praktykiatrem.game.tictactoe.graphic;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Filip Ró¿añski
 */
public class WinDialog extends javax.swing.JDialog {
	private IDialogOwner owner;

	/**
	 * Creates new form WinDialog
	 */
	public WinDialog(java.awt.Frame parent, String name, IDialogOwner owner,
			boolean modal) {
		super(parent, modal);
		this.owner = owner;
		initComponents(name);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(String name) {

		okButton = new javax.swing.JButton();
		winLabel = new javax.swing.JLabel();
		nameLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		okButton.setText("OK");
		okButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});

		winLabel.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
		winLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		winLabel.setText("Wygra³:");

		nameLabel.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
		nameLabel.setText(name);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(64, 64,
																		64)
																.addComponent(
																		winLabel,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		97,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		nameLabel,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		91,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(139,
																		139,
																		139)
																.addComponent(
																		okButton)))
								.addContainerGap(68, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(33, 33, 33)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														winLabel,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														42,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														nameLabel,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														42,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addComponent(okButton,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(22, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
		owner.clicked();
		dispose();
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel nameLabel;
	private javax.swing.JButton okButton;
	private javax.swing.JLabel winLabel;
	// End of variables declaration
}
