package pl.praktykiatrem.game.uniElements.dialogs;

import pl.praktykiatrem.game.tictactoe.graphic.interfaces.IDialogOwner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Filip Ró¿añski
 */
public class MessageDialog extends javax.swing.JDialog {
	private IDialogOwner owner;

	/**
	 * Creates new form MessageDialog
	 */
	public MessageDialog(java.awt.Frame parent, String text,
			IDialogOwner owner, boolean modal) {
		super(parent, modal);
		this.owner = owner;
		initComponents(text);
		setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * */

	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(String text) {

		textLabel = new javax.swing.JLabel();
		okButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		textLabel.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
		textLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		textLabel.setText(text);

		okButton.setText("OK");
		okButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(96, 96,
																		96)
																.addComponent(
																		textLabel,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		144,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(126,
																		126,
																		126)
																.addComponent(
																		okButton,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		82,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(97, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(26, 26, 26)
								.addComponent(textLabel,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										31,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										43, Short.MAX_VALUE)
								.addComponent(okButton,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(25, 25, 25)));

		pack();
	}// </editor-fold>

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
		owner.clicked();
		dispose();
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel textLabel;
	private javax.swing.JButton okButton;
	// End of variables declaration
}
